version: '3.3'

services:
  red:
    image: redis
    ports:
      - 6379:6379
  web:
    build: .
    command: python /usr/src/My_site/manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/usr/src/My_site
    ports:
      - 8000:8000
    depends_on:
      - red
  celery:
    build: .
    command: celery -A Shop_site worker -l info
    volumes:
      - .:/usr/src/My_site
    depends_on:
      - red
  celery_beat:
    build: .
    command: celery -A Shop_site beat -l info
    volumes:
      - .:/usr/src/My_site
    depends_on:
      - red