# Generated by Django 3.2.3 on 2021-05-23 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cathegory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('photo', models.ImageField(blank=True, upload_to='product/%Y/%m/%d')),
                ('price', models.DecimalField(decimal_places=1, max_digits=10)),
                ('discount', models.BooleanField(default=False)),
                ('percent', models.DecimalField(blank=True, decimal_places=0, max_digits=2)),
                ('consist', models.TextField(blank=True, max_length=700)),
                ('weight_size', models.CharField(max_length=20)),
                ('v_nal', models.DecimalField(decimal_places=0, max_digits=4)),
                ('proteins', models.DecimalField(decimal_places=1, max_digits=3)),
                ('fats', models.DecimalField(decimal_places=1, max_digits=3)),
                ('uglevody', models.DecimalField(decimal_places=1, max_digits=3)),
                ('calories', models.DecimalField(decimal_places=1, max_digits=3)),
                ('cathegory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cathegory')),
                ('country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='shop.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HozProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('photo', models.ImageField(blank=True, upload_to='product/%Y/%m/%d')),
                ('price', models.DecimalField(decimal_places=1, max_digits=10)),
                ('discount', models.BooleanField(default=False)),
                ('percent', models.DecimalField(blank=True, decimal_places=0, max_digits=2)),
                ('consist', models.TextField(blank=True, max_length=700)),
                ('weight', models.CharField(max_length=20)),
                ('cathegory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cathegory')),
                ('country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='shop.country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
