# Generated by Django 3.2.3 on 2021-05-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hozproduct',
            name='final_price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='final_price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
