# Generated by Django 3.2.3 on 2021-05-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210523_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hozproduct',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
