# Generated by Django 3.2.3 on 2021-05-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210525_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hozproduct',
            name='percent',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='percent',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2),
        ),
    ]
