# Generated by Django 3.2.3 on 2021-06-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210611_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hozproduct',
            name='v_nal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='v_nal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
    ]
