# Generated by Django 3.2.3 on 2021-06-13 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_zakaz'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='trans_date',
            field=models.DateField(default=datetime.date(2021, 6, 13)),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='date_create',
            field=models.DateField(auto_now_add=True),
        ),
    ]
