# Generated by Django 3.2.3 on 2021-06-13 13:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20210613_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz',
            name='trans_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 13, 13, 56, 7, 255249, tzinfo=utc)),
        ),
    ]
