# Generated by Django 3.2.3 on 2021-06-13 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_zakaz_trans_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz',
            name='trans_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
