# Generated by Django 3.2.3 on 2021-06-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_zakaz_trans_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hozproduct',
            name='Type',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='Type',
            field=models.BooleanField(default=0),
        ),
    ]
