# Generated by Django 3.2.3 on 2021-06-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20210615_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='hoz_products',
            field=models.ManyToManyField(blank=True, to='shop.HozProduct'),
        ),
        migrations.AddField(
            model_name='zakaz',
            name='products',
            field=models.ManyToManyField(blank=True, to='shop.Product'),
        ),
    ]
