# Generated by Django 3.2.3 on 2021-06-16 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20210615_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zakaz',
            name='hoz_products',
        ),
        migrations.RemoveField(
            model_name='zakaz',
            name='products',
        ),
        migrations.CreateModel(
            name='ZakazCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cathegory', models.BooleanField()),
                ('count', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('hozproduct', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.hozproduct')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product')),
                ('zakaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.zakaz')),
            ],
        ),
    ]
