# Generated by Django 3.2.3 on 2021-06-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20210616_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='cathegory',
            name='photo',
            field=models.ImageField(blank=True, upload_to='cathegory'),
        ),
        migrations.AddField(
            model_name='hozcathegory',
            name='photo',
            field=models.ImageField(blank=True, upload_to='cathegory'),
        ),
        migrations.AlterField(
            model_name='hozproduct',
            name='photo',
            field=models.ImageField(upload_to='product/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='product/%Y/%m/%d'),
        ),
    ]
