# Generated by Django 3.2.3 on 2021-06-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20210621_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='status',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='Товар передан'),
        ),
    ]
