# Generated by Django 3.2.3 on 2021-06-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_zakaz_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz',
            name='status',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('C', 'Cancel')], default='N', max_length=1, verbose_name='Товар передан'),
        ),
    ]
