# Generated by Django 3.2.3 on 2021-06-29 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_alter_zakaz_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hozproduct',
            name='v_nal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='v_nal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
